sudo: false
language: node_js
node_js:
  - 10
  - 12
  - 14

cache:
  bundle: true
  directories:
    - node_modules

{{#if lerna}}
jobs:
  include:
#    - stage: Document deploy
#      allow_failure: true
#      script: npm run site:build
#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: ${GH_TOKEN} # Set in travis-ci.org dashboard
#        local_dir: _site/public
    - stage: Unit testing
      before_script: npm install codecov --no-save
      script: npm test -- --coverage
      after_script: codecov --token=$CODECOV_TOKEN
{{else}}
{{#if lerna}}
before_script:
  - npm run bootstrap
{{/if}}
{{#if test}}
script:
  - npm install codecov nyc --no-save
{{#or rollup babel}}
  - npm run test-ci -- --coverage
{{else}}
{{#if isJest}}
  - npm test -- --coverage
{{else}}
  - npx nyc $(npm bin)/ava
{{/if}}
{{/or}}
after_script:
{{#if isJest}}
  - npx codecov --token=$CODECOV_TOKEN
{{else}}
  - npx nyc --reporter=text-lcov | npx codecov --token=$CODECOV_TOKEN --pipe
{{/if}}
{{/if}}
{{/if}}
